apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-static-canary
  labels:
    app: lms-static
    version: canary
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-static
      version: canary
  template:
    metadata:
      labels:
        app: lms-static
        version: canary
    spec:
      containers:
      - name: lms-static-container
        image: k8sworkshopcertd.azurecr.io/lms-static:v1.0.10    
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret 
